### ISSUE TITLE
Set up linting

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-boilerplate-express-apollo#2]
### Motivation

It would be great to have a common code format specification.

### Proposed solution

* Use ESLint recommended set up and adjust the code by that.
* implement npm script called lint to run lint (without the fix option) to be able to joint this check for pre-commit/CI pipeline

### Additional context

*  [.eslintrc.json](https://eslint.org/docs/user-guide/configuring

**Comment by alenakhineika** [comment]
Want to submit a PR. Can I have pushing permission for `alenakhineika`?
